version: "3.9"
services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: shortener
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app_pw
    ports:
      - "5444:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
